apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}-static-gateway-peering
data:
  gateway-peering.js: |
{{ .Files.Get "static/gateway-peering.js" | indent 4 -}}
