apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ template "dynamic-gateway-service.fullname" . }}-init-config-apic
  labels:
      app: {{ template "dynamic-gateway-service.fullname" . }}
      chart: {{ .Chart.Name}}-{{ .Chart.Version | replace "+" "_" }}
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
data:
# See _apiconnectGateway.tpl for this definition
{{- include "apiconnectDomainConfig" . | indent 4 }}
